"""Embedded report-sent backfill cohorts (from CBTW + Celebal Excel).

Build-time source:
- CBTW registrations.xlsx / Men -> engagement_id 16
- Celebal registrations.xlsx / Men -> engagement_id 72
- Celebal registrations.xlsx / Women -> engagement_id 73

Runtime: no Excel required.
Rule: for every Excel user row, all four channels are marked sent
(tick OR blank both mean status=sent). User resolved by phone (create if missing).
"""

from __future__ import annotations

BACKFILL_COHORTS: list[dict] = [
    {
        "engagement_id": 16,
        "label": "CBTW Pvt ltd",
        "rows": [
        {
            'first_name': 'Gnanaprakash',
            'last_name': 'Selvaraj',
            'phone': '8050000283',
            'email': 'gselvaraj@cbtw.tech',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'ARCHANA',
            'last_name': 'BOMMAKANTI',
            'phone': '9441502057',
            'email': 'abommakanti@cbtw.tech',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'GEETHA',
            'last_name': 'LAKSHMANAIAH',
            'phone': '8667885812',
            'email': 'glakshmanaiah@cbtw.tech',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'BHAVYALATHA',
            'last_name': 'VISHAKANTA',
            'phone': '9880136660',
            'email': 'bvishakanta@cbtw.tech',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'SUBBULAKSHMI',
            'last_name': 'SANKARANARAYANAN',
            'phone': '9566306610',
            'email': 'ssankaranarayanan@cbtw.tech',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'RAVI KISHORE',
            'last_name': 'GANJI',
            'phone': '7095904913',
            'email': 'rganji@cbtw.tech',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'SHARAD',
            'last_name': 'HARAPANHALLI',
            'phone': '9738287989',
            'email': 'sharapanahalli@cbtw.tech',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'RATHEESH KUMAR',
            'last_name': 'UPENDRA',
            'phone': '8296938771',
            'email': 'rupendra@cbtw.tech',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'RAHUL ASHOK',
            'last_name': 'MAHIND',
            'phone': '9764177779',
            'email': 'rmahind@cbtw.tech',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'SUDHA RANI',
            'last_name': 'ALLURI',
            'phone': '8105709232',
            'email': 'salluri@cbtw.tech',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'NAKSHETHRA',
            'last_name': 'SUGANTH',
            'phone': '9738408679',
            'email': 'nsuganth@cbtw.tech',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'UMAR',
            'last_name': 'SHARIEF',
            'phone': '7259371179',
            'email': 'usharief@cbtw.tech',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'SARANYA',
            'last_name': 'SREEDHAR',
            'phone': '9611803493',
            'email': 'ssreedhar@cbtw.tech',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
    ],
    },
    {
        "engagement_id": 72,
        "label": "Celebal Technologies Male",
        "rows": [
        {
            'first_name': 'SYLVESTER',
            'last_name': 'FERNANDES',
            'phone': '9928492120',
            'email': 'sylvester.fernandes@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Samir',
            'last_name': 'Iraqi',
            'phone': '9819927782',
            'email': 'samir.iraqi@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Rohit',
            'last_name': 'Bongu',
            'phone': '9000588852',
            'email': 'Rohit.Bongu@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Rajib',
            'last_name': 'Goon',
            'phone': '8597678334',
            'email': 'rajib.goon@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'sandeep',
            'last_name': 'singh',
            'phone': '8800478012',
            'email': 'letter2sandeepsingh@gmail.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'amit',
            'last_name': 'sharma',
            'phone': '7387890336',
            'email': 'amit.sharma@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Shashibhushan',
            'last_name': 'Kolhe',
            'phone': '9823736801',
            'email': 'shashibhushan.kolhe@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Dhyanesh',
            'last_name': 'Babu',
            'phone': '9740565566',
            'email': 'dhyanesh.babu@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'HITENDRA',
            'last_name': 'SAINI',
            'phone': '7014803392',
            'email': 'hitendra.saini@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Mandar',
            'last_name': 'Rane',
            'phone': '9768212196',
            'email': 'mandar.rane@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Sundararajan',
            'last_name': 'Nagarajan',
            'phone': '9790878085',
            'email': 'n.sundararajan1983@gmail.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Varoun',
            'last_name': 'Jindal',
            'phone': '9930751305',
            'email': 'varounjindal@gmail.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Ripudaman Singh',
            'last_name': 'Rajawat',
            'phone': '8952953777',
            'email': 'ripudamansingh.rajawat@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'ADARSH KUMAR',
            'last_name': 'MEHNDIRATTA',
            'phone': '7014377534',
            'email': 'Adarsh.mehndiratta@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Rajeev',
            'last_name': 'Jain',
            'phone': '9828074000',
            'email': 'rajeev.jain1@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Arijit',
            'last_name': 'Sen',
            'phone': '9748017946',
            'email': 'arijit.sen@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Biswaroop',
            'last_name': 'Roy',
            'phone': '8826538046',
            'email': 'biswaroop.roy@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Sandip',
            'last_name': 'Kamble',
            'phone': '7559369500',
            'email': 'sandip.kamble@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Anirudh',
            'last_name': 'Singh',
            'phone': '9829861100',
            'email': 'anirudhs1902@gmail.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Rajiv',
            'last_name': 'Ranjan',
            'phone': '9910340054',
            'email': 'rajiv.ranjan@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Nachiket',
            'last_name': 'Gangakhedkar',
            'phone': '9970861292',
            'email': 'nachiket.gangakhedkar@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Gurbachan',
            'last_name': 'Sethi',
            'phone': '9711149719',
            'email': 'sethigurbachan2013@gmail.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Chinmay',
            'last_name': 'Malhotra',
            'phone': '9828255232',
            'email': 'chinmay.malhotra@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Avtarit',
            'last_name': 'Talwar',
            'phone': '9928847000',
            'email': 'avtarit.talwar@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Sabarinathan',
            'last_name': 'Sampath',
            'phone': '7299997288',
            'email': 'sabarinathan.sampath@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Ashish',
            'last_name': 'Ranjan',
            'phone': '9741328967',
            'email': 'ashish.ranjan@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'ALOK',
            'last_name': 'JAIN',
            'phone': '9829079715',
            'email': 'alok1.jain@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Nikhil',
            'last_name': 'Mathur',
            'phone': '9999985723',
            'email': 'nikhil.mathur1@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Gaive',
            'last_name': 'Gandhi',
            'phone': '9820409923',
            'email': 'gaive.gandhi@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Mohinder Singh',
            'last_name': 'Bansal',
            'phone': '9811466998',
            'email': 'mohindersingh.bansal@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'mandar pradeep',
            'last_name': 'gokhale',
            'phone': '9823124999',
            'email': 'mandar.gokhale@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Sarthak',
            'last_name': 'Shah',
            'phone': '8780603108',
            'email': 'sarthak.shah@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Nidarshan',
            'last_name': 'Nukul',
            'phone': '9620788811',
            'email': 'nidarshan.nukul@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Piyush',
            'last_name': 'Gupta',
            'phone': '9958994309',
            'email': 'piyush.gupta@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Dhrubabrata',
            'last_name': 'Singha Roy',
            'phone': '9999803029',
            'email': 'dhruv.roy@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Rakesh',
            'last_name': 'Raut',
            'phone': '9664440123',
            'email': 'rakesh.raut@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Pankaj',
            'last_name': 'Kumar',
            'phone': '9456258302',
            'email': 'pankaj.kumar@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Rajesh',
            'last_name': 'Bhujbal',
            'phone': '9766722800',
            'email': 'rajesh.bhujbal@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Khushboo',
            'last_name': 'Thakran',
            'phone': '8800843076',
            'email': 'khushboo.thakran@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
    ],
    },
    {
        "engagement_id": 73,
        "label": "Celebal Technologies Female",
        "rows": [
        {
            'first_name': 'Yogita',
            'last_name': 'Garg',
            'phone': '9650129222',
            'email': 'yogita.garg@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Pankti',
            'last_name': 'Bindal',
            'phone': '9879536754',
            'email': 'pankti.bindal@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Monika',
            'last_name': 'Joshi',
            'phone': '9828234440',
            'email': 'monika.joshi@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Sunita',
            'last_name': 'Rath',
            'phone': '7606892636',
            'email': 'sunita.rath@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
    ],
    },
]
