"""Embedded report-sent backfill cohorts (from CBTW + Celebal Excel).

Build-time source:
- CBTW registrations.xlsx / Men -> engagement_id 16
- Celebal registrations.xlsx / Men -> engagement_id 72
- Celebal registrations.xlsx / Women -> engagement_id 73

Runtime: no Excel required.
Rule: tick (True) = mark that channel status=sent; blank (False) = ignore.
User resolved by phone (create if missing), then enroll in engagement_id.
"""

from __future__ import annotations

BACKFILL_COHORTS: list[dict] = [
    {
        "engagement_id": 16,
        "label": 'CBTW Pvt ltd',
        "rows": [
        {
            'first_name': 'Gnanaprakash',
            'last_name': 'Selvaraj',
            'phone': '8050000283',
            'email': 'gselvaraj@cbtw.tech',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'ARCHANA',
            'last_name': 'BOMMAKANTI',
            'phone': '9441502057',
            'email': 'abommakanti@cbtw.tech',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'VIVEKANAND',
            'last_name': 'DHARMAVARAPU',
            'phone': '9177498889',
            'email': 'vdharmavarapu@cbtw.tech',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'GEETHA',
            'last_name': 'LAKSHMANAIAH',
            'phone': '8667885812',
            'email': 'glakshmanaiah@cbtw.tech',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'BHAVYALATHA',
            'last_name': 'VISHAKANTA',
            'phone': '9880136660',
            'email': 'bvishakanta@cbtw.tech',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'RAVI KISHORE',
            'last_name': 'GANJI',
            'phone': '7095904913',
            'email': 'rganji@cbtw.tech',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'SHARAD',
            'last_name': 'HARAPANHALLI',
            'phone': '9738287989',
            'email': 'sharapanahalli@cbtw.tech',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'JAIGANESH',
            'last_name': 'THYAGARAJAN',
            'phone': '8892739176',
            'email': 'jthyagarajan@cbtw.tech',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'RATHEESH KUMAR',
            'last_name': 'UPENDRA',
            'phone': '8296938771',
            'email': 'rupendra@cbtw.tech',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'RAHUL ASHOK',
            'last_name': 'MAHIND',
            'phone': '9764177779',
            'email': 'rmahind@cbtw.tech',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'SUDHA RANI',
            'last_name': 'ALLURI',
            'phone': '8105709232',
            'email': 'salluri@cbtw.tech',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'NAKSHETHRA',
            'last_name': 'SUGANTH',
            'phone': '9738408679',
            'email': 'nsuganth@cbtw.tech',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'UMAR',
            'last_name': 'SHARIEF',
            'phone': '7259371179',
            'email': 'usharief@cbtw.tech',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'SARANYA',
            'last_name': 'SREEDHAR',
            'phone': '9611803493',
            'email': 'ssreedhar@cbtw.tech',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
    ],
    },
    {
        "engagement_id": 72,
        "label": 'Celebal Technologies Male',
        "rows": [
        {
            'first_name': 'SYLVESTER',
            'last_name': 'FERNANDES',
            'phone': '9928492120',
            'email': 'sylvester.fernandes@celebaltech.com',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'Shyamnarayan',
            'last_name': 'Yadav',
            'phone': '8097853813',
            'email': 'shyamny13@gmail.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Samir',
            'last_name': 'Iraqi',
            'phone': '9819927782',
            'email': 'samir.iraqi@celebaltech.com',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'Amit',
            'last_name': 'Chakraborty',
            'phone': '9818115602',
            'email': 'amit.chakraborty@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Satchidanand',
            'last_name': 'Sewalkar',
            'phone': '9890922346',
            'email': 'satchidanandsuresh.sewalkar@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Sanjay',
            'last_name': 'Patil',
            'phone': '7219411611',
            'email': 'sanjay.patil@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Sachidanand',
            'last_name': 'Tripathi',
            'phone': '9810993480',
            'email': 'sachidanand.tripathi@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'ASHOK',
            'last_name': 'KUMAR',
            'phone': '9999567138',
            'email': 'ashok.kumar@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Abhinav',
            'last_name': 'chawla',
            'phone': '8806252666',
            'email': 'Abhinav.chawla@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Kunal',
            'last_name': 'Kelkar',
            'phone': '9561087366',
            'email': 'kunal.kelkar@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Ashish',
            'last_name': 'Mittal',
            'phone': '9717394413',
            'email': 'ashish.mittal@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'sandeep',
            'last_name': 'singh',
            'phone': '8800478012',
            'email': 'letter2sandeepsingh@gmail.com',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'Manish',
            'last_name': 'Tak',
            'phone': '9819307404',
            'email': 'manish.tak@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Vishal',
            'last_name': 'Deshmukh',
            'phone': '9850882029',
            'email': 'vishal.deshmukh@celebaletech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Sudhir',
            'last_name': 'Bhardwaj',
            'phone': '9212100909',
            'email': 'sudhirbig@gmail.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Dhyanesh',
            'last_name': 'Babu',
            'phone': '9740565566',
            'email': 'dhyanesh.babu@celebaltech.com',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'Nimish',
            'last_name': 'Thakkar',
            'phone': '7977029217',
            'email': 'nimish.thakkar@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'HITENDRA',
            'last_name': 'SAINI',
            'phone': '7014803392',
            'email': 'hitendra.saini@celebaltech.com',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'Naresh',
            'last_name': 'Kumar',
            'phone': '9717565858',
            'email': 'naresh.kumar@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Mandar',
            'last_name': 'Rane',
            'phone': '9768212196',
            'email': 'mandar.rane@celebaltech.com',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'Vasu',
            'last_name': 'Tirumalasetty',
            'phone': '9019859721',
            'email': 'vasu.kumar@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Yogesh Kumar',
            'last_name': 'Singh',
            'phone': '9404016209',
            'email': 'yogeshkumar.singh@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Ghanshyam',
            'last_name': 'Kumawat',
            'phone': '9982686610',
            'email': 'Ghanshyam.kumawat@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Varoun',
            'last_name': 'Jindal',
            'phone': '9930751305',
            'email': 'varounjindal@gmail.com',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'Ripudaman Singh',
            'last_name': 'Rajawat',
            'phone': '8952953777',
            'email': 'ripudamansingh.rajawat@celebaltech.com',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'Lowhile',
            'last_name': 'Mengi',
            'phone': '9811217771',
            'email': 'lowhile.mengi@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Rajeev',
            'last_name': 'Jain',
            'phone': '9828074000',
            'email': 'rajeev.jain1@celebaltech.com',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'Tilak',
            'last_name': 'Kumar Maddula',
            'phone': '9241341360',
            'email': 'tilak.kumar@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Srinivasa Rao',
            'last_name': 'Pesala',
            'phone': '9686942083',
            'email': 'srinivasa.pesala@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Abhishek',
            'last_name': 'Sharma',
            'phone': '9828014466',
            'email': 'abhishek.sharma6@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'NIKHIL',
            'last_name': 'PEREIRA',
            'phone': '9769714310',
            'email': 'nikhil.pereira@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'SOMIL',
            'last_name': 'VIJAY',
            'phone': '7023828722',
            'email': 'somil.vijay@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'GIRISH',
            'last_name': 'PEDNEKAR',
            'phone': '9833541158',
            'email': 'girish.pednekar@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Arijit',
            'last_name': 'Sen',
            'phone': '9748017946',
            'email': 'arijit.sen@celebaltech.com',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'Nilesh',
            'last_name': 'Shelar',
            'phone': '8999508568',
            'email': 'nilesh.shelar@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Puneet',
            'last_name': 'Mahajan',
            'phone': '9828807772',
            'email': 'puneet.mahajan@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Feroz',
            'last_name': 'Zaidi',
            'phone': '9818577575',
            'email': 'feroz.zaidi@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Sandip',
            'last_name': 'Kamble',
            'phone': '7559369500',
            'email': 'sandip.kamble@celebaltech.com',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'Haridev',
            'last_name': 'Sharma',
            'phone': '9414235101',
            'email': 'haridev.sharma@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Anirudh',
            'last_name': 'Singh',
            'phone': '9829861100',
            'email': 'anirudhs1902@gmail.com',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'Rajiv',
            'last_name': 'Ranjan',
            'phone': '9910340054',
            'email': 'rajiv.ranjan@celebaltech.com',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'SANJAY',
            'last_name': 'SHARMA',
            'phone': '9711266220',
            'email': 'sanjay.sharma@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Nachiket',
            'last_name': 'Gangakhedkar',
            'phone': '9970861292',
            'email': 'nachiket.gangakhedkar@celebaltech.com',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'Gagandeep',
            'last_name': 'Sanyal',
            'phone': '8233335430',
            'email': 'gagandeep.sanyal@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Abhijeet',
            'last_name': 'Ray',
            'phone': '9999149509',
            'email': 'abhijeet.ray@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Chinmay',
            'last_name': 'Malhotra',
            'phone': '9828255232',
            'email': 'chinmay.malhotra@celebaltech.com',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'Avtarit',
            'last_name': 'Talwar',
            'phone': '9928847000',
            'email': 'avtarit.talwar@celebaltech.com',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'Mohit',
            'last_name': 'Kumar',
            'phone': '9928739538',
            'email': 'mohit.kumar@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Ajay',
            'last_name': 'Ballani',
            'phone': '7760707581',
            'email': 'ajaykumar.ballani@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Vishwa Kalyan',
            'last_name': 'Dahagam',
            'phone': '9964838045',
            'email': 'vishwakalyan.dahagam@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Vivek',
            'last_name': 'Shah',
            'phone': '9909512725',
            'email': 'vivek.shah@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'ALOK',
            'last_name': 'JAIN',
            'phone': '9829079715',
            'email': 'alok1.jain@celebaltech.com',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'VIPIN',
            'last_name': 'SHARMA',
            'phone': '9910592901',
            'email': 'vipin.sharma@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Gaive',
            'last_name': 'Gandhi',
            'phone': '9820409923',
            'email': 'gaive.gandhi@celebaltech.com',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'Mohinder Singh',
            'last_name': 'Bansal',
            'phone': '9811466998',
            'email': 'mohindersingh.bansal@celebaltech.com',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'mandar pradeep',
            'last_name': 'gokhale',
            'phone': '9823124999',
            'email': 'mandar.gokhale@celebaltech.com',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'Sarthak',
            'last_name': 'Shah',
            'phone': '8780603108',
            'email': 'sarthak.shah@celebaltech.com',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'Nidarshan',
            'last_name': 'Nukul',
            'phone': '9620788811',
            'email': 'nidarshan.nukul@celebaltech.com',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'Piyush',
            'last_name': 'Gupta',
            'phone': '9958994309',
            'email': 'piyush.gupta@celebaltech.com',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'Dhrubabrata',
            'last_name': 'Singha Roy',
            'phone': '9999803029',
            'email': 'dhruv.roy@celebaltech.com',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'Rakesh',
            'last_name': 'Raut',
            'phone': '9664440123',
            'email': 'rakesh.raut@celebaltech.com',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'Pankaj',
            'last_name': 'Kumar',
            'phone': '9456258302',
            'email': 'pankaj.kumar@celebaltech.com',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'Rajesh',
            'last_name': 'Bhujbal',
            'phone': '9766722800',
            'email': 'rajesh.bhujbal@celebaltech.com',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'Khushboo',
            'last_name': 'Thakran',
            'phone': '8800843076',
            'email': 'khushboo.thakran@celebaltech.com',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
    ],
    },
    {
        "engagement_id": 73,
        "label": 'Celebal Technologies Female',
        "rows": [
        {
            'first_name': 'Sonali',
            'last_name': 'Chothe',
            'phone': '9226269249',
            'email': 'sonali.tarlekar@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Reema',
            'last_name': 'Khandelwal',
            'phone': '8208297094',
            'email': 'reema.khandelwal@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Shweta',
            'last_name': 'Singhal',
            'phone': '9828505583',
            'email': 'shweta.singhal@celebal.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Madhuri',
            'last_name': 'Palaji',
            'phone': '9502178820',
            'email': 'madhuri.palaji@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Pankti',
            'last_name': 'Bindal',
            'phone': '9879536754',
            'email': 'pankti.bindal@celebaltech.com',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'Niyati',
            'last_name': 'Pandit',
            'phone': '9890322861',
            'email': 'niyati.pandit@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Heena',
            'last_name': 'Jain',
            'phone': '8949234038',
            'email': 'heena.jain@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Manisha',
            'last_name': 'Vatsyayan',
            'phone': '9650313634',
            'email': 'manisha.vatsyayan@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Anjali',
            'last_name': 'Gandhi',
            'phone': '8619410484',
            'email': 'anjali.gandhi@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Tejaswini Raghavendra',
            'last_name': 'Kamath',
            'phone': '9611590672',
            'email': 'tejaswini.kamath@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Roopa',
            'last_name': 'Garg',
            'phone': '7892622748',
            'email': 'roopa.garg@celebaltech.com',
            'email_blood': True,
            'email_bioai': True,
            'whatsapp_blood': True,
            'whatsapp_bioai': True,
        },
        {
            'first_name': 'Monika',
            'last_name': 'Joshi',
            'phone': '9828234440',
            'email': 'monika.joshi@celebaltech.com',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
        {
            'first_name': 'Sunita',
            'last_name': 'Rath',
            'phone': '7606892636',
            'email': 'sunita.rath@celebaltech.com',
            'email_blood': True,
            'email_bioai': False,
            'whatsapp_blood': True,
            'whatsapp_bioai': False,
        },
    ],
    },
]
